### ISSUE TITLE
Accept GLOB patterns (wildcard pathname) for input

### ISSUE THREAD

**Issue by kiura24metrics** [favadi/protoc-go-inject-tag#21] opened 2018-08-02 18:41 UTC
It would be nice to have this the same way as protoc does (however, if this is gonna be refactored to be a plugin it would be even better and wouldnt need GLOB)

**Comment by kiura24metrics** [comment] 2018-08-02 18:46
from what I understand it could easily be implemented using `files, err := filepath.Glob()` in `main.go` and looping over files. Three lines of code.

**Comment by adamkissvcc** [comment] 2021-02-11 12:01
I think this is a duplicate of: https://github.com/favadi/protoc-go-inject-tag/issues/37

**Closed** 2021-08-10 13:52 UTC
